destination: /oe-training-default/ai2-llm/preprocessed/nvidia_OpenMathInstruct-2/v0/train/allenai/dolma2-tokenizer
documents:
  - s3://ai2-llm/pretraining-data/sources/nvidia_OpenMathInstruct-2/v0/documents/train/*.gz

processes: 188
seed: 3920
ring_size: 8
batch_size: 20_000
max_size: 4_294_967_296
dtype: uint32

tokenizer:
  name_or_path: allenai/dolma2-tokenizer
  bos_token_id: null
  eos_token_id: 100257
  pad_token_id: 100277
  segment_before_tokenization: false
  encode_special_tokens: true