run_name: v1_7-urlfilter-1b-150b
seed: 6198
dry_run: false
# 10 days
time_limit: 864000

wandb:
  name: ${run_name}
  project: olmo-small

model:
  d_model: 2048
  n_heads: 16
  n_layers: 16
  mlp_ratio: 8
  weight_tying: false
  alibi: false
  rope: true
  flash_attention: true
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 2048
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 50279
  pad_token_id: 1
  init_device: meta
  init_fn: mitchell

compile:
  fullgraph: false

optimizer:
  name: adamw
  learning_rate: 4.0e-4
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  t_warmup: 2000
  t_max: 46_667 # 200B tokens
  alpha_f: 0.1
  # 7B has these, worth adding?
  # grad_clip_warmup_steps: 1000
  # grad_clip_warmup_factor: 10.0

tokenizer:
  identifier: tokenizers/allenai_gpt-neox-olmo-dolma-v1_5.json
  truncate_direction: right

save_folder: runs/${run_name}
remote_save_folder: s3://ai2-llm/checkpoints/1b/${wandb.group}/${run_name}
save_overwrite: true
# Sharded checkpoints (best for restarts)
save_interval: 1000
save_num_checkpoints_to_keep: 10
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 5000
save_num_unsharded_checkpoints_to_keep: -1

# load_path: s3://ai2-llm/checkpoints/1b/olmo-small-dolma-150B-mcli/step14950/

max_duration: 35_000  # 150B tokens
global_train_batch_size: 2048
device_train_microbatch_size: 8

precision: amp_bf16

fsdp:
  wrapping_strategy: by_block
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

eval_interval: ${save_interval}
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  # lump all the small datasets together (we still get separate metrics).
  - label: v3-small-ppl-validation
    data:
      drop_last: true
      datasets:
        v3-small-c4_en-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy
        v3-small-dolma_books-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_books/val/part-0-00000.npy
        v3-small-dolma_common-crawl-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_common-crawl/val/part-0-00000.npy
        v3-small-dolma_pes2o-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_pes2o/val/part-0-00000.npy
        v3-small-dolma_reddit-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_reddit/val/part-0-00000.npy
        v3-small-dolma_stack-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_stack/val/part-0-00000.npy
        v3-small-dolma_wiki-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_wiki/val/part-0-00000.npy
        v3-small-ice-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/ice/val/part-0-00000.npy
        v3-small-m2d2_s2orc-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/m2d2_s2orc/val/part-0-00000.npy
        pile:
        - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/pile/val/part-0-00000.npy
        v3-small-wikitext_103-validation:
          - s3://ai2-llm/eval-data/perplexity/v3_small_gptneox20b/wikitext_103/val/part-0-00000.npy

  - label: v2-small-ppl-validation
    data:
      datasets:
        v2-small-4chan-validation:
          - s3://ai2-llm/eval-data/perplexity/v2_small_gptneox20b/4chan/val.npy
        v2-small-c4_100_domains-validation:
          - s3://ai2-llm/eval-data/perplexity/v2_small_gptneox20b/c4_100_domains/val.npy
        v2-small-c4_en-validation:
          - s3://ai2-llm/eval-data/perplexity/v2_small_gptneox20b/c4_en/val.npy
        v2-small-gab-validation:
          - s3://ai2-llm/eval-data/perplexity/v2_small_gptneox20b/gab/val.npy
        v2-small-ice-validation:
          - s3://ai2-llm/eval-data/perplexity/v2_small_gptneox20b/ice/val.npy
        v2-small-m2d2_s2orc-validation:
          - s3://ai2-llm/eval-data/perplexity/v2_small_gptneox20b/m2d2_s2orc/val.npy
        v2-small-m2d2_wiki-validation:
          - s3://ai2-llm/eval-data/perplexity/v2_small_gptneox20b/m2d2_wiki/val.npy
        v2-small-manosphere-validation:
          - s3://ai2-llm/eval-data/perplexity/v2_small_gptneox20b/manosphere/val.npy
        v2-small-mc4_en-validation:
          - s3://ai2-llm/eval-data/perplexity/v2_small_gptneox20b/mc4_en/val.npy
        v2-small-pile-validation:
          - s3://ai2-llm/eval-data/perplexity/v2_small_gptneox20b/pile/val.npy
        v2-small-ptb-validation:
          - s3://ai2-llm/eval-data/perplexity/v2_small_gptneox20b/ptb/val.npy
        v2-small-twitterAEE-validation:
          - s3://ai2-llm/eval-data/perplexity/v2_small_gptneox20b/twitterAEE/val.npy
        v2-small-wikitext_103-validation:
          - s3://ai2-llm/eval-data/perplexity/v2_small_gptneox20b/wikitext_103/val.npy

  ##########################
  # Downstream evaluations #
  ##########################
  - label: piqa
    type: downstream

  - label: hellaswag
    type: downstream

  - label: winogrande
    type: downstream

  - label: openbook_qa
    type: downstream

  # - label: boolq  # requires implemention of the pmi_dc matrix
    # type: downstream

  - label: sciq
    type: downstream

  - label: arc_easy
    type: downstream

  # - label: arc_challenge  # requires implemention of the pmi_dc matrix
  #   type: downstream

  - label: copa
    type: downstream

  - label: rte
    type: downstream

  - label: commitment_bank
    type: downstream

  - label: mrpc
    type: downstream

  - label: sst2
    type: downstream

data:
  pad_direction: right
  num_workers: 16
  drop_last: true
  pin_memory: true
  prefetch_factor: 1
  persistent_workers: true
  timeout: 0
  paths:
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-00-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-01-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-02-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-03-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-04-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-05-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-06-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-07-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-08-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-09-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-10-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-11-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-12-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-13-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-14-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-15-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-16-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-16-00001.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-17-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-18-00000.npy
    - s3://ai2-llm/preprocessed/olmo-mix/v1_6-300G-decon-urlfilter/gpt-neox-olmo-dolma-v1_6/part-19-00000.npy
