save_folder: "/tmp/olmo-train-tiny"
model:
  d_model: 128
  n_heads: 2
  n_layers: 2
  mlp_ratio: 1
  alibi: false
  alibi_bias_max: 8.0
  attention_dropout: 0.1
  attention_layer_norm: false
  residual_dropout: 0.1
  embedding_dropout: 0.1
  max_sequence_length: 2048
  vocab_size: 50257
  eos_token_id: 50256
  pad_token_id: 50256
  init_device: null
  init_std: 0.02
optimizer:
  learning_rate: 0.001
scheduler:
  name: "cosine_with_warmup"
  t_warmup: 10
data:
  paths:
    - "test_fixtures/mup-sample-data/part-010-00002.npy"
  persistent_workers: false
  num_workers: 0
  prefetch_factor: null
tokenizer:
  identifier: "gpt2"
save_overwrite: true
max_duration: 4
global_train_batch_size: 4
device_train_microbatch_size: 4
