run_name: peteish7-anneal-from-477000-100B-lb_v0
seed: 7201
dry_run: false

wandb:
  name: ${run_name}
  project: spicy-olmo-medium
  group: ${run_name}

model:
  d_model: 4096
  n_heads: 32
  n_layers: 32
  mlp_hidden_size: 22016
  weight_tying: false
  alibi: false
  rope: true
  rope_theta: 500000
  flash_attention: true
  attention_dropout: 0.0
  include_bias: false
  block_type: sequential
  layer_norm_type: rms
  layer_norm_with_affine: true
  layer_norm_eps: 1e-6
  bias_for_layer_norm: false
  attention_layer_norm: true
  attention_layer_norm_with_affine: true
  norm_after: true
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 4096
  vocab_size: 100278
  embedding_size: 100352
  eos_token_id: 100257
  pad_token_id: 100277
  init_device: meta
  init_fn: normal
  init_std: 0.02
  init_cutoff_factor: 3

softmax_auxiliary_loss: true
auxiliary_loss_multiplier: 1e-5
fused_loss: true

compile: null

optimizer:
  name: adamw
  learning_rate: 0.00041414
  weight_decay: 0.1
  eps: 1e-8
  decay_norm_and_bias: true
  decay_embeddings: false
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  units: steps
  name: linear_with_warmup
  t_warmup: 0
  alpha_f: 0

tokenizer:
  identifier: tokenizers/allenai_dolma2.json
  truncate_direction: right

remote_save_folder: gs://allennlp-dustins/checkpoints/${run_name}
save_overwrite: false

save_interval: 1000
save_num_checkpoints_to_keep: -1
sharded_checkpointer: olmo_core

save_interval_unsharded: null
save_num_unsharded_checkpoints_to_keep: -1

load_path: gs://ai2-llm/checkpoints/OLMo-medium/peteish7-medlr/step477000

restore_dataloader: false
no_pre_train_checkpoint: true

max_duration: 100e9T
stop_at: 23852                  # round(100e9 / (1024 * 4096)) + 10
global_train_batch_size: 1024
device_train_microbatch_size: 2

precision: amp_bf16

fsdp:
  wrapping_strategy: by_block_and_size
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 1

gen1_gc_interval: 1

eval_interval: 1000
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  ##########################
  # Downstream evaluations #
  ##########################
  - label: mmlu_stem_mc_5shot
    type: downstream

  - label: mmlu_humanities_mc_5shot
    type: downstream

  - label: mmlu_social_sciences_mc_5shot
    type: downstream

  - label: mmlu_other_mc_5shot
    type: downstream

  - label: arc_challenge_mc_5shot
    type: downstream

  - label: arc_challenge_mc_5shot_bpb
    type: downstream

  - label: arc_easy_mc_5shot
    type: downstream

  - label: arc_easy_mc_5shot_bpb
    type: downstream

  - label: boolq_mc_5shot
    type: downstream

  - label: boolq_mc_5shot_bpb
    type: downstream

  - label: csqa_mc_5shot
    type: downstream

  - label: csqa_mc_5shot_bpb
    type: downstream

  - label: hellaswag_mc_5shot
    type: downstream

  - label: hellaswag_mc_5shot_bpb
    type: downstream

  - label: openbookqa_mc_5shot
    type: downstream

  - label: openbookqa_mc_5shot_bpb
    type: downstream

  - label: piqa_mc_5shot
    type: downstream

  - label: piqa_mc_5shot_bpb
    type: downstream

  - label: socialiqa_mc_5shot
    type: downstream

  - label: socialiqa_mc_5shot_bpb
    type: downstream

  - label: winogrande_mc_5shot
    type: downstream

  - label: winogrande_mc_5shot_bpb
    type: downstream

  - label: basic_arithmetic
    type: downstream

  - label: hellaswag
    type: downstream

data:
  pad_direction: right
  # generate_doc_lengths: true
  num_workers: 32
  drop_last: true
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true
  memmap_dtype: uint32
  timeout: 0
  instance_filter:
    repetition_max_period: 13
    repetition_min_period: 1
    repetition_max_count: 32
  paths:
     # lb_v0
    - gs://allennlp-dustins/preprocessed/lb_v0/part-000-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-001-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-002-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-003-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-004-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-005-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-006-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-007-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-008-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-009-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-010-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-011-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-012-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-013-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-014-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-015-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-016-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-017-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-018-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-019-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-020-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-021-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-022-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-023-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-024-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-025-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-026-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-027-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-028-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-029-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-030-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-031-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-032-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-033-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-034-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-035-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-036-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-037-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-038-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-039-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-040-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-041-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-042-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-043-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-044-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-045-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-046-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-047-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-048-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-049-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-050-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-051-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-052-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-053-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-054-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-055-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-056-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-057-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-058-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-059-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-060-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-061-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-062-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-063-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-064-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-065-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-066-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-067-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-068-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-070-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-071-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-072-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-073-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-074-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-075-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-076-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-077-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-078-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-079-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-080-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-081-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-082-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-083-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-084-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-085-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-086-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-087-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-088-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-089-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-090-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-091-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-092-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-093-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-094-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-095-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-096-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-097-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-098-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-099-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-100-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-101-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-102-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-103-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-104-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-105-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-106-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-107-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-108-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-109-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-110-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-111-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-112-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-113-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-114-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-115-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-116-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-117-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-118-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-119-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-120-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-121-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-122-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-123-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-124-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-125-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-126-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-127-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-128-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-129-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-130-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-131-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-132-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-133-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-134-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-135-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-136-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-137-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-138-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-139-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-140-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-141-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-142-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-143-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-144-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-145-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-146-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-147-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-148-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-149-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-150-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-151-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-152-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-153-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-154-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-155-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-156-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-157-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-158-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-159-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-160-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-161-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-162-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-163-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-164-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-165-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-166-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-167-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-168-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-169-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-170-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-171-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-172-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-173-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-174-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-175-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-176-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-177-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-178-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-179-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-180-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-181-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-182-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-183-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-184-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-185-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-186-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-187-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-188-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-189-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-190-00000.npy
    - gs://allennlp-dustins/preprocessed/lb_v0/part-191-00000.npy
