run_name: long_contexts_dolma_v0.6_cont_train_2T_steps_10B
seed: 61394
dry_run: false

wandb:
  name: ${run_name}
  project: olmo-long-contexts
  group: long_contexts_dolma_v0.6_cont_train_2T_steps_10B

model:
  d_model: 4096
  n_heads: 32
  n_layers: 32
  # mlp_ratio: 6
  mlp_hidden_size: 22016
  weight_tying: false
  alibi: false
  rope: true
  flash_attention: true
  attention_dropout: 0.0
  attention_layer_norm: false
  clip_qkv: null
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 16384
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 0
  pad_token_id: 1
  init_device: meta
  init_fn: mitchell

compile: null

optimizer:
  name: adamw
  learning_rate: 2e-5
  weight_decay: 0.1
  decay_norm_and_bias: true
  decay_embeddings: true
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: constant
  t_warmup: 0
  alpha_f: 0

tokenizer:
  identifier: tokenizers/allenai_gpt-neox-olmo-dolma-v1_5.json
  truncate_direction: right

save_folder: /data
save_overwrite: false
remote_save_folder: s3://ai2-llm/checkpoints/dustins/long-contexts/${run_name}
# Sharded checkpoints (best for restarts)
save_interval: 119
save_num_checkpoints_to_keep: -1

save_interval_unsharded: null
save_num_unsharded_checkpoints_to_keep: -1

restore_dataloader: false

# 2T token checkpoint for new 7B model; we call this v1.7 to match the Dolma data.
load_path: s3://ai2-llm/checkpoints/OLMo-medium/mitchish7/step477000-unsharded

no_pre_train_checkpoint: true
reset_optimizer_state: false
reset_trainer_state: true

max_duration: 5e9T
stop_at: 595
global_train_batch_size: 512
device_train_microbatch_size: 1
time_limit: null

precision: amp_bf16

distributed_strategy: fsdp

fsdp:
  wrapping_strategy: by_block_and_size
  sharding_strategy: SHARD_GRAD_OP
  precision: mixed


max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 1

eval_interval: ${save_interval}
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  - label: all-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        c4_en-validation:
          - /weka/oe-training-default/ai2-llm/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy
        dolma_books-validation:
          - /weka/oe-training-default/ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_books/val/part-0-00000.npy
        dolma_common-crawl-validation:
          - /weka/oe-training-default/ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_common-crawl/val/part-0-00000.npy
        dolma_pes2o-validation:
          - /weka/oe-training-default/ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_pes2o/val/part-0-00000.npy
        dolma_reddit-validation:
          - /weka/oe-training-default/ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_reddit/val/part-0-00000.npy
        dolma_stack-validation:
          - /weka/oe-training-default/ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_stack/val/part-0-00000.npy
        dolma_wiki-validation:
          - /weka/oe-training-default/ai2-llm/eval-data/perplexity/v3_small_gptneox20b/dolma_wiki/val/part-0-00000.npy
        ice-validation:
          - /weka/oe-training-default/ai2-llm/eval-data/perplexity/v3_small_gptneox20b/ice/val/part-0-00000.npy
        m2d2_s2orc-validation:
          - /weka/oe-training-default/ai2-llm/eval-data/perplexity/v3_small_gptneox20b/m2d2_s2orc/val/part-0-00000.npy
        pile-validation:
          - /weka/oe-training-default/ai2-llm/eval-data/perplexity/v3_small_gptneox20b/pile/val/part-0-00000.npy
        wikitext_103-validation:
          - /weka/oe-training-default/ai2-llm/eval-data/perplexity/v3_small_gptneox20b/wikitext_103/val/part-0-00000.npy

 ##########################
  # Downstream evaluations #
  ##########################
  - label: piqa
    type: downstream

  - label: hellaswag
    type: downstream

  - label: winogrande
    type: downstream

  - label: openbook_qa
    type: downstream
 
  - label: sciq
    type: downstream

  - label: arc_easy
    type: downstream

  - label: commonsense_qa
    type: downstream

  - label: social_iqa
    type: downstream

  # Doesn't work from cache.
  # - label: basic_arithmetic
  #   type: downstream

  - label: mmlu_stem_var
    type: downstream

  - label: mmlu_humanities_var
    type: downstream

  - label: mmlu_social_sciences_var
    type: downstream

  - label: mmlu_other_var
    type: downstream

  - label: mmlu_stem_mc_5shot
    type: downstream

  - label: mmlu_humanities_mc_5shot
    type: downstream

  - label: mmlu_social_sciences_mc_5shot
    type: downstream

  - label: mmlu_other_mc_5shot
    type: downstream

  - label: mmlu_stem_mc_5shot_test
    type: downstream

  - label: mmlu_humanities_mc_5shot_test
    type: downstream

  - label: mmlu_social_sciences_mc_5shot_test
    type: downstream

  - label: mmlu_other_mc_5shot_test
    type: downstream

  - label: basic_arithmetic
    type: downstream

  - label: trivia_qa_wiki_ppl
    type: downstream

  - label: natural_qs_open_ppl
    type: downstream

  - label: arc_easy_ppl
    type: downstream

data:
  pad_direction: right
  num_workers: 32
  drop_last: true
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true
  timeout: 0
  paths:
    # ~> Long-context subset (50 GT)
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-01-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-02-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-03-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-04-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-06-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-05-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-07-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-08-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-09-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-10-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-11-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-12-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-13-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-14-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-15-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-16-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-17-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-18-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-19-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-20-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-21-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-22-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-23-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-24-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-25-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-26-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-27-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-28-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-29-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-30-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-31-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-32-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-33-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-34-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-35-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-36-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-37-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-38-00000.npy
    - /weka/oe-training-default/ai2-llm/preprocessed/long_contexts/long_contexts_v0p7/part-39-00000.npy